language: c
os:
  - linux
  - osx
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install gimme; fi
  - eval "$(gimme stable)"
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - asdf plugin-add kubecfg ./
  - asdf list-all kubecfg
  - asdf plugin-test kubecfg ./ 'kubecfg version'
