language: c
before_script:
  - eval "$(gimme stable)"
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - asdf plugin-add kubecfg ./
  - asdf list-all kubecfg
  - asdf plugin-test kubecfg ./ 'kubecfg version'
os:
  - linux
  - osx
