language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
  - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod +x ~/bin/gimme
script:
  - eval "$(gimme stable)"
  - asdf plugin-add kubecfg ./
  - asdf list-all kubecfg
  - asdf plugin-test kubecfg ./ 'kubecfg version'
os:
  - linux
  - osx
