language: go
go:
  - 1.8
  - 1.9
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - asdf plugin-add kubecfg ./
  - asdf list-all kubecfg
  - asdf plugin-test kubecfg ./ 'kubecfg version'
os:
  - linux
  - osx
